apiVersion: v1
kind: Secret
metadata:
    name: demoapp-credentials
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:GZHe/yU=,iv:57vWcbKeTM1CHvaDYh8lMPFiKpJ579K4qPvx7qQtwhc=,tag:x2fZZ5TlN3HyiJlDifBgeg==,type:str]
    password: ENC[AES256_GCM,data:z28rhypWX1LwCw==,iv:IkIosASO5i95gQGHhphN1YS6kNbxLR5SB+Q4kkPwVZg=,tag:dnJZicyKq70XIE/fv9bGaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://bigbang-demo-enbuild.vault.azure.net
          name: sops-key
          version: 3e7781ddc080466d960d16aa8b520836
          created_at: "2022-02-18T14:13:09Z"
          enc: q_MDHhy5Bx68BEpqt_HkOerQxqkSXgHbgYpNh_HtIWa5JXWaDqxwYhPtV4Nw99r7113ba-sjhTSY-yjKedFnT0EUk7IiK1p8XNCB9WY5FpjYCckvvA5OrutRF_hBQqUxkGtNKN5cZnVMTo7Lmlgs6p-eDNDO5pDCuSArPHw7j9uCmi4RjaiffR8s5z7Zt36jE8FxHRNiCI7HvOXCPhezgvaeC7nSwblX_sPUW47Ve7nGbDOahHOZWnHr9Wx8IjEjPSimVp5a9rbqEeDG70rZDks-cAamRITdY40XA0Ab-bp7ykBluJOjRPKce7f4cahAaP0lpYSejAyBHy0nTT2PgA
    hc_vault: []
    age: []
    lastmodified: "2022-02-18T14:13:13Z"
    mac: ENC[AES256_GCM,data:caXdQ8l8a1zspwLkGqh3WqhFqnt6j3PUw3C/9TRjvuGmU0hm8i2KoRS6W4RINPFkqeSUfKt79x3/zD7ZNwImAcxfUT/V3lgrvOFaObL8dFHQUI0ljRviT1Ai4TTxmUXiEpQ+kjpk+QR+RfNqG9CcUlGEL36JlwX4Tmf4KZbAces=,iv:+PHp9YwkdjU7V9aiKNZSBLQrK4eCIS1+xF8v+5I+VE0=,tag:3SSy7o0lEGAcTwJO/UcQVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
